import Head from "next/head";
import { Inter } from "@next/font/google";
import { trpc } from "../utils/trpc";

export default function Home() {
	const { data } = trpc.hello.useQuery({ text: "client" });
	console.log(data);
	return (
		<>
			<Head>
				<title>trpc</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Hello world</h1>
		</>
	);
}
