import Head from "next/head";
import { Inter } from "@next/font/google";
import { trpc } from "../utils/trpc";

export default function Home() {
	const test = trpc.shopping.test.useQuery({ text: "is it working" });
	const test5 = trpc.shopping2.test5.useQuery({ text: "which test" });
	return (
		<>
			<Head>
				<title>trpc</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{test5.data?.test}</h1>
		</>
	);
}
